name: Code Coverage
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: 'xdebug'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-suggest --no-interaction

      - name: Run Tests
        run: vendor/bin/pest --coverage

      - name: Copy coverage report to build folder
        run: cp -r build/coverage ./coverage/

      - name: Deploy Coverage Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          publish_dir: ./coverage/
